'use strict';
/**
 * Kagura encounter tables.
 *
 * One entry per atlas place plus routes 1-14. `types` mirror the atlas catch
 * types; `common` lists the base of each line that defines the place (the
 * engine also mixes in any species of those types and picks the evolution
 * stage from the player's badge count); `rare` holds the surprises.
 * `wild` names the Discord channels (no '#') where something can jump out,
 * `trainers` the trainer classes met there, and `noTrainers` indoor channels
 * where a trainer battle would make no sense.
 *
 * The region is open world: nothing here depends on gym order, and `tier`
 * in the atlas is flavour only. Starter and pseudo-legendary lines appear
 * only in `rare` and at no more than two places each. No legendaries or
 * mythicals anywhere; a handful of Ultra Beasts / Paradox Pokemon sit in
 * places with a story reason (Abyss HQ, the Sunken Bell, Aether's labs).
 */
module.exports = {
  region: 'kagura',
  locations: {
    // ---------------------------------------------------------------- Hinode
    'sakura': {
      name: 'Sakura Town',
      channels: ['poke-center', 'sakura-lab', 'sakura-square', 'shrine-steps', 'sakura-mart', 'blossom-road', 'the-old-well', 'sakura-houses', 'sakura-beach', 'sakura-ferry', 'cynthias-house'],
      types: ['Normal', 'Bug', 'Flying', 'Grass'],
      wild: ['blossom-road', 'shrine-steps', 'the-old-well', 'sakura-beach'],
      trainers: ['youngster', 'lass', 'schoolkid', 'bugcatcher'],
      noTrainers: ['poke-center', 'sakura-lab', 'sakura-mart', 'sakura-houses', 'cynthias-house'],
      common: ['Pidgey', 'Sentret', 'Hoppip', 'Caterpie', 'Weedle', 'Oddish', 'Bidoof', 'Starly', 'Sewaddle', 'Wurmple', 'Petilil', 'Cottonee', 'Sunkern', 'Skwovet', 'Wingull', 'Shellder', 'Krabby'],
      rare: ['Eevee', 'Mimikyu', 'Smeargle', 'Munchlax'],
    },
    'station': {
      name: 'Kagura Station',
      channels: ['train-station', 'platform-two', 'ticket-hall', 'station-market', 'freight-yard', 'lost-property'],
      types: ['Normal', 'Flying', 'Steel', 'Electric'],
      wild: ['platform-two', 'freight-yard', 'lost-property'],
      trainers: ['worker', 'gentleman', 'pokefan', 'policeman', 'schoolkid', 'guitarist'],
      noTrainers: ['ticket-hall', 'lost-property'],
      common: ['Rattata', 'Pidove', 'Meowth', 'Magnemite', 'Voltorb', 'Klink', 'Plusle', 'Minun', 'Pawmi', 'Tadbulb', 'Zigzagoon', 'Trubbish', 'Elekid'],
      rare: ['Rotom', 'Porygon', 'Meowth-Galar', 'Varoom'],
    },
    'amber': {
      name: 'Amber Fields',
      channels: ['the-fields', 'glasshouse-gym', 'farm-shop', 'mill-pond', 'the-barns', 'scarecrow-lane'],
      types: ['Grass', 'Bug', 'Ground', 'Normal'],
      wild: ['the-fields', 'mill-pond', 'the-barns', 'scarecrow-lane'],
      trainers: ['picnicker', 'camper', 'bugcatcher', 'breeder', 'worker', 'youngster'],
      noTrainers: ['farm-shop'],
      common: ['Diglett', 'Sunkern', 'Paras', 'Ledyba', 'Nincada', 'Kricketot', 'Bellsprout', 'Seedot', 'Lechonk', 'Nymble', 'Smoliv', 'Bounsweet', 'Miltank', 'Mudbray', 'Rellor'],
      rare: ['Tepig', 'Torchic', 'Tauros-Paldea-Combat', 'Cacnea'],
    },
    'minato': {
      name: 'Minato Harbour',
      channels: ['docks', 'ferry-terminal', 'fish-market', 'harbour-mart', 'harbour-gym', 'poke-center-minato', 'the-breakwater', 'warehouse-row', 'harbour-inn'],
      types: ['Water', 'Flying', 'Poison', 'Normal'],
      wild: ['docks', 'the-breakwater', 'warehouse-row'],
      trainers: ['sailor', 'fisherman', 'swimmer', 'swimmerf', 'tuber', 'worker', 'abyssalgrunt'],
      noTrainers: ['ferry-terminal', 'fish-market', 'harbour-mart', 'poke-center-minato', 'harbour-inn'],
      common: ['Tentacool', 'Magikarp', 'Wingull', 'Krabby', 'Grimer', 'Horsea', 'Shellos', 'Trubbish', 'Glameow', 'Arrokuda', 'Poliwag'],
      rare: ['Oshawott', 'Cramorant', 'Meowth-Alola'],
    },
    'longsands': {
      name: 'Long Sands',
      channels: ['long-sands', 'the-shallows-south'],
      types: ['Water', 'Normal', 'Flying', 'Ground'],
      wild: ['long-sands', 'the-shallows-south'],
      trainers: ['swimmer', 'swimmerf', 'tuber', 'picnicker', 'beauty', 'fisherman'],
      common: ['Wingull', 'Krabby', 'Shellder', 'Horsea', 'Psyduck', 'Sandshrew', 'Wiglett', 'Pyukumuku', 'Buizel', 'Finizen', 'Azurill'],
      rare: ['Squirtle', 'Sandygast', 'Mantyke', 'Wailord'],
    },
    'millpond': {
      name: 'The Mill Pond',
      channels: ['the-mill-pond', 'the-jetty'],
      types: ['Water', 'Bug', 'Grass', 'Normal'],
      wild: ['the-mill-pond', 'the-jetty'],
      trainers: ['fisherman', 'youngster', 'lass', 'bugcatcher', 'picnicker', 'tuber'],
      common: ['Magikarp', 'Goldeen', 'Poliwag', 'Lotad', 'Surskit', 'Wooper', 'Bidoof', 'Ducklett', 'Tympole', 'Chewtle', 'Budew', 'Combee'],
      rare: ['Froakie', 'Sobble', 'Feebas'],
    },
    'reservoir': {
      name: 'Kagura Reservoir',
      channels: ['kagura-reservoir', 'the-dam-wall'],
      types: ['Water', 'Normal', 'Flying'],
      wild: ['kagura-reservoir', 'the-dam-wall'],
      trainers: ['fisherman', 'policeman', 'worker', 'birdkeeper', 'youngster'],
      common: ['Magikarp', 'Barboach', 'Basculin', 'Psyduck', 'Buizel', 'Ducklett', 'Taillow', 'Hoothoot', 'Bidoof', 'Chewtle', 'Spearow'],
      rare: ['Quaxly', 'Gyarados', 'Wishiwashi', 'Qwilfish-Hisui'],
    },
    'stables': {
      name: 'Kagura Stables',
      channels: ['the-stables', 'the-paddocks', 'tack-room'],
      types: ['Normal', 'Grass', 'Ground'],
      wild: ['the-stables', 'the-paddocks'],
      trainers: ['breeder', 'camper', 'picnicker', 'pokefan', 'richboy', 'lady'],
      noTrainers: ['tack-room'],
      common: ['Ponyta', 'Tauros', 'Miltank', 'Skiddo', 'Mudbray', 'Deerling', 'Blitzle', 'Wooloo', 'Doduo', 'Stantler', 'Lillipup', 'Buneary'],
      rare: ['Ponyta-Galar', 'Bouffalant', 'Tauros-Paldea-Blaze', 'Ditto'],
    },
    'daycare': {
      name: 'The Day Care',
      channels: ['the-day-care', 'the-walled-garden'],
      types: ['Normal', 'Fairy', 'Grass'],
      wild: ['the-day-care', 'the-walled-garden'],
      trainers: ['breeder', 'pokefan', 'teacher'],
      noTrainers: ['the-day-care'],
      common: ['Igglybuff', 'Happiny', 'Budew', 'Azurill', 'Skitty', 'Snubbull', 'Flabébé', 'Cottonee', 'Fidough', 'Minccino', 'Tandemaus', 'Petilil'],
      rare: ['Snivy', 'Sprigatito', 'Togepi', 'Ditto'],
    },
    'harefield': {
      name: "Hare's Meadow",
      channels: ['hares-meadow', 'the-long-grass'],
      types: ['Normal', 'Bug', 'Grass', 'Flying'],
      wild: ['hares-meadow', 'the-long-grass'],
      trainers: ['youngster', 'lass', 'bugcatcher', 'picnicker', 'camper'],
      common: ['Bunnelby', 'Buneary', 'Nidoran-F', 'Nidoran-M', 'Scatterbug', 'Cutiefly', 'Fletchling', 'Patrat', 'Tarountula', 'Pikipek', 'Gossifleur', 'Yungoos', 'Sunkern'],
      rare: ['Scorbunny', 'Chikorita', 'Farfetch’d', 'Pinsir'],
    },
    'windbreaks': {
      name: 'The Windbreaks',
      channels: ['the-windbreaks', 'hedgerow-walk'],
      types: ['Normal', 'Flying', 'Bug'],
      wild: ['the-windbreaks', 'hedgerow-walk'],
      trainers: ['birdkeeper', 'bugcatcher', 'youngster', 'cyclist', 'backpacker'],
      common: ['Spearow', 'Starly', 'Rookidee', 'Volbeat', 'Illumise', 'Whismur', 'Kricketot', 'Dunsparce', 'Aipom', 'Skwovet', 'Squawkabilly', 'Glameow', 'Burmy'],
      rare: ['Chatot', 'Kecleon', 'Scyther'],
    },
    'saltmarsh': {
      name: 'Saltmarsh Flats',
      channels: ['saltmarsh-flats', 'the-creeks'],
      types: ['Water', 'Ground', 'Poison', 'Flying'],
      wild: ['saltmarsh-flats', 'the-creeks'],
      trainers: ['fisherman', 'birdkeeper', 'ranger', 'rangerf', 'backpacker'],
      common: ['Wooper', 'Stunfisk', 'Grimer', 'Croagunk', 'Tentacool', 'Doduo', 'Ducklett', 'Shellos', 'Tympole', 'Skorupi', 'Ekans', 'Seviper'],
      rare: ['Mudkip', 'Totodile', 'Stunfisk-Galar', 'Wooper-Paldea'],
    },

    // ------------------------------------------------------------ Kogarashi
    'victory': {
      name: 'Victory Road',
      channels: ['victory-gatehouse', 'the-lower-slopes', 'first-cave', 'the-cliff-path', 'rope-bridges', 'second-cave', 'final-climb'],
      types: ['Rock', 'Ground', 'Dragon', 'Fighting'],
      wild: ['the-lower-slopes', 'first-cave', 'the-cliff-path', 'rope-bridges', 'second-cave', 'final-climb'],
      trainers: ['acetrainer', 'acetrainerf', 'veteran', 'hiker', 'blackbelt', 'battlegirl', 'dragontamer'],
      noTrainers: ['victory-gatehouse'],
      common: ['Geodude', 'Machop', 'Makuhita', 'Timburr', 'Drilbur', 'Mienfoo', 'Rockruff', 'Noibat', 'Zubat', 'Onix', 'Axew', 'Rhyhorn', 'Druddigon'],
      rare: ['Larvitar', 'Jangmo-o', 'Hawlucha', 'Tyrunt'],
    },
    'league': {
      name: 'Kagura League',
      channels: ['league-lobby', 'league-centre', 'league-mart', 'hall-the-first', 'hall-the-second', 'hall-the-third', 'hall-the-fourth', 'champions-chamber', 'hall-of-fame'],
      types: ['Psychic', 'Dragon', 'Steel', 'Ice'],
      wild: [],
      trainers: ['acetrainer', 'acetrainerf', 'veteran', 'dragontamer', 'psychicf'],
      noTrainers: ['league-centre', 'league-mart', 'hall-of-fame'],
      common: ['Ralts', 'Bronzor', 'Axew', 'Snorunt', 'Swablu', 'Sneasel', 'Vulpix-Alola', 'Hatenna', 'Cryogonal', 'Aron', 'Honedge', 'Noibat'],
      rare: ['Duraludon', 'Cyclizar', 'Froslass'],
    },
    'mirrortarn': {
      name: 'Mirror Tarn',
      channels: ['mirror-tarn', 'the-shingle-shore'],
      types: ['Water', 'Ice', 'Rock', 'Fairy'],
      wild: ['mirror-tarn', 'the-shingle-shore'],
      trainers: ['fisherman', 'skier', 'hiker', 'beauty', 'backpacker'],
      common: ['Seel', 'Spheal', 'Snorunt', 'Swinub', 'Magikarp', 'Poliwag', 'Barboach', 'Azurill', 'Bergmite', 'Snom', 'Shellder'],
      rare: ['Dratini', 'Eiscue', 'Vulpix-Alola'],
    },
    'mine': {
      name: 'The Old Mine',
      channels: ['the-old-mine', 'upper-galleries', 'the-water-line'],
      types: ['Rock', 'Steel', 'Ground', 'Dark'],
      wild: ['the-old-mine', 'upper-galleries', 'the-water-line'],
      trainers: ['hiker', 'worker', 'ruinmaniac', 'punk', 'backpacker'],
      common: ['Zubat', 'Geodude', 'Roggenrola', 'Aron', 'Nosepass', 'Woobat', 'Nacli', 'Pawniard', 'Rolycoly', 'Diglett-Alola', 'Tinkatink', 'Barboach', 'Litwick'],
      rare: ['Sableye', 'Larvitar', 'Gimmighoul'],
    },
    'ruins': {
      name: 'The Standing Stones',
      // The Psychic gym meets here (moved from N's Castle). Like the other gyms, its channel has trainers but no wild Pokémon.
      channels: ['the-standing-stones', 'stones-gym', 'the-fallen-ninth'],
      types: ['Psychic', 'Rock', 'Ghost', 'Fairy'],
      wild: ['the-standing-stones', 'the-fallen-ninth'],
      trainers: ['ruinmaniac', 'psychic', 'psychicf', 'hexmaniac', 'sage'],
      common: ['Baltoy', 'Bronzor', 'Unown', 'Elgyem', 'Yamask', 'Golett', 'Gastly', 'Spritzee', 'Girafarig', 'Mime Jr.', 'Natu'],
      rare: ['Yamask-Galar', 'Solrock', 'Stonjourner'],
    },
    'pinewood': {
      name: 'The Pinewood',
      channels: ['the-pinewood', 'planting-rows'],
      types: ['Bug', 'Grass', 'Flying', 'Fighting'],
      wild: ['the-pinewood', 'planting-rows'],
      trainers: ['bugcatcher', 'camper', 'ranger', 'blackbelt', 'ninjaboy', 'hiker'],
      common: ['Pineco', 'Spinarak', 'Hoothoot', 'Karrablast', 'Shelmet', 'Mankey', 'Teddiursa', 'Seedot', 'Combee', 'Taillow', 'Mienfoo'],
      rare: ['Turtwig', 'Rowlet', 'Scyther', 'Passimian'],
    },
    'heath': {
      name: 'Kogarashi Heath',
      channels: ['kogarashi-heath', 'the-tors'],
      types: ['Rock', 'Flying', 'Ice', 'Ground'],
      wild: ['kogarashi-heath', 'the-tors'],
      trainers: ['hiker', 'birdkeeper', 'camper', 'backpacker', 'skier'],
      common: ['Rockruff', 'Rhyhorn', 'Gligar', 'Swinub', 'Vullaby', 'Drilbur', 'Cubchoo', 'Bonsly', 'Sandshrew', 'Murkrow', 'Spearow'],
      rare: ['Bagon', 'Aerodactyl', 'Absol'],
    },
    'ghost': {
      name: 'Ghost Woods',
      channels: ['the-treeline', 'deep-woods', 'lantern-clearing', 'woods-gym', 'the-shrine-ruin', 'where-the-paths-move'],
      types: ['Ghost', 'Dark', 'Poison', 'Grass'],
      wild: ['the-treeline', 'deep-woods', 'lantern-clearing', 'the-shrine-ruin', 'where-the-paths-move'],
      trainers: ['hexmaniac', 'channeler', 'psychic', 'bugcatcher', 'punk', 'ninjaboy'],
      common: ['Phantump', 'Pumpkaboo', 'Gastly', 'Misdreavus', 'Duskull', 'Litwick', 'Murkrow', 'Zubat', 'Oddish', 'Foongus', 'Spinarak', 'Stunky', 'Morelull', 'Impidimp', 'Bramblin', 'Greavard'],
      rare: ['Dreepy', 'Rowlet', 'Poltchageist'],
    },
    'castle': {
      name: "N's Castle",
      channels: ['castle-gate', 'throne-room', 'library', 'undercroft', 'the-battlements', 'kings-quarters', 'castle-library'],
      types: ['Psychic', 'Dark', 'Steel', 'Ghost'],
      wild: ['castle-gate', 'undercroft', 'the-battlements'],
      trainers: ['psychic', 'psychicf', 'hexmaniac', 'gentleman', 'lady', 'ninjaboy', 'ruinmaniac'],
      noTrainers: ['library', 'kings-quarters'],
      common: ['Abra', 'Drowzee', 'Purrloin', 'Zorua', 'Gothita', 'Solosis', 'Espurr', 'Honedge', 'Pawniard', 'Woobat', 'Mawile', 'Shuppet', 'Sinistea'],
      rare: ['Deino', 'Mr. Mime', 'Indeedee'],
    },
    'silver': {
      name: 'Mt. Silver',
      channels: ['foothills', 'peak', 'silver-cave', 'the-ice-shelf', 'climbers-hut'],
      types: ['Ice', 'Rock', 'Fighting', 'Dragon'],
      wild: ['foothills', 'peak', 'silver-cave', 'the-ice-shelf'],
      trainers: ['hiker', 'skier', 'blackbelt', 'battlegirl', 'veteran', 'acetrainer', 'dragontamer'],
      noTrainers: ['climbers-hut'],
      common: ['Sneasel', 'Phanpy', 'Sandshrew-Alola', 'Vulpix-Alola', 'Snover', 'Cetoddle', 'Machop', 'Onix', 'Axew', 'Druddigon', 'Bergmite', 'Zubat'],
      rare: ['Frigibax', 'Amaura', 'Darumaka-Galar'],
    },

    // --------------------------------------------------------------- Shiomi
    'hinomiya': {
      name: 'Hinomiya Shrine',
      channels: ['hinomiya-shrine', 'the-shrine-stair', 'the-rim-platform'],
      types: ['Fire', 'Psychic', 'Ghost', 'Dragon'],
      wild: ['hinomiya-shrine', 'the-shrine-stair', 'the-rim-platform'],
      trainers: ['channeler', 'sage', 'kimonogirl', 'hexmaniac', 'firebreather', 'psychicf'],
      noTrainers: ['hinomiya-shrine'],
      common: ['Vulpix', 'Ponyta', 'Litwick', 'Duskull', 'Natu', 'Misdreavus', 'Spoink', 'Chingling', 'Numel', 'Salandit', 'Sinistea', 'Shuppet'],
      rare: ['Fennekin', 'Oricorio', 'Charcadet', 'Drampa'],
    },
    'midori': {
      name: 'Midori Jungle',
      channels: ['midori-jungle', 'the-green-side', 'the-rain-shadow'],
      types: ['Grass', 'Bug', 'Poison', 'Water'],
      wild: ['midori-jungle', 'the-green-side', 'the-rain-shadow'],
      trainers: ['bugcatcher', 'ranger', 'rangerf', 'backpacker', 'picnicker'],
      common: ['Tangela', 'Venonat', 'Yanma', 'Surskit', 'Carnivine', 'Croagunk', 'Foongus', 'Dewpider', 'Morelull', 'Fomantis', 'Ekans', 'Lotad', 'Grubbin', 'Toedscool', 'Tropius'],
      rare: ['Bulbasaur', 'Goomy', 'Heracross', 'Comfey'],
    },
    'kuroihama': {
      name: 'Kuroihama',
      channels: ['kuroihama', 'the-black-sand'],
      types: ['Fire', 'Water', 'Rock', 'Dark'],
      wild: ['kuroihama', 'the-black-sand'],
      trainers: ['firebreather', 'swimmer', 'fisherman', 'punk', 'delinquent'],
      common: ['Slugma', 'Corphish', 'Carvanha', 'Binacle', 'Dwebble', 'Houndour', 'Poochyena', 'Tentacool', 'Wimpod', 'Clauncher', 'Magby', 'Heatmor'],
      rare: ['Fuecoco', 'Tirtouga', 'Turtonator'],
    },
    'craterpool': {
      name: 'The Crater Pool',
      channels: ['the-crater-pool'],
      types: ['Fire', 'Water', 'Poison'],
      wild: ['the-crater-pool'],
      trainers: ['scientist', 'firebreather', 'hiker', 'fisherman'],
      common: ['Grimer', 'Koffing', 'Slugma', 'Skrelp', 'Mareanie', 'Salandit', 'Wooper-Paldea', 'Stunky', 'Toedscool', 'Glimmet', 'Heatmor'],
      rare: ['Toxel', 'Grimer-Alola', 'Sizzlipede'],
    },
    'onsen': {
      name: 'Ashen Onsen',
      channels: ['ashen-onsen', 'the-outdoor-bath', 'the-guest-rooms'],
      types: ['Water', 'Fire', 'Fairy'],
      wild: ['ashen-onsen', 'the-outdoor-bath'],
      trainers: ['beauty', 'gentleman', 'lady', 'kimonogirl', 'richboy', 'youngcouple'],
      noTrainers: ['the-guest-rooms', 'the-outdoor-bath'],
      common: ['Slowpoke', 'Torkoal', 'Numel', 'Magby', 'Litleo', 'Spritzee', 'Swirlix', 'Milcery', 'Azurill', 'Buizel', 'Pansear', 'Panpour'],
      rare: ['Snorlax', 'Slowpoke-Galar', 'Mr. Mime'],
    },
    'observatory': {
      name: 'Storm Observatory',
      channels: ['storm-observatory', 'the-weather-logs'],
      types: ['Flying', 'Electric', 'Ice'],
      wild: ['storm-observatory'],
      trainers: ['scientist', 'birdkeeper', 'hiker', 'skier'],
      noTrainers: ['the-weather-logs'],
      common: ['Mareep', 'Electrike', 'Shinx', 'Emolga', 'Wattrel', 'Snover', 'Delibird', 'Cryogonal', 'Rufflet', 'Noibat', 'Skarmory'],
      rare: ['Castform', 'Rotom-Frost', 'Bombirdier'],
    },
    'ashfields': {
      name: 'The Ashfields',
      channels: ['the-ashfields', 'warm-ground'],
      types: ['Fire', 'Ground', 'Rock', 'Poison'],
      wild: ['the-ashfields', 'warm-ground'],
      trainers: ['hiker', 'firebreather', 'kindler', 'backpacker', 'worker'],
      common: ['Trapinch', 'Cubone', 'Numel', 'Koffing', 'Growlithe', 'Silicobra', 'Skorupi', 'Onix', 'Glimmet', 'Capsakid', 'Rolycoly'],
      rare: ['Cyndaquil', 'Larvesta', 'Marowak-Alola'],
    },
    'barrens': {
      name: 'Sulphur Barrens',
      channels: ['sulphur-barrens', 'the-vents-north'],
      types: ['Poison', 'Fire', 'Ground', 'Steel'],
      wild: ['sulphur-barrens', 'the-vents-north'],
      trainers: ['scientist', 'worker', 'hiker', 'hexmaniac', 'punk'],
      common: ['Ekans', 'Venipede', 'Salandit', 'Stunky', 'Trubbish', 'Varoom', 'Glimmet', 'Heatmor', 'Durant', 'Drilbur', 'Toedscool', 'Koffing'],
      rare: ['Weezing-Galar', 'Toxel', 'Orthworm'],
    },
    'ember': {
      name: 'Ember Hollow',
      channels: ['caldera-town', 'ash-flats', 'ember-gym', 'poke-center-ember', 'ember-mart', 'hot-springs', 'the-vents', 'obsidian-works'],
      types: ['Fire', 'Ground', 'Rock', 'Poison'],
      wild: ['ash-flats', 'the-vents', 'hot-springs'],
      trainers: ['firebreather', 'kindler', 'worker', 'hiker', 'scientist', 'artist'],
      noTrainers: ['poke-center-ember', 'ember-mart', 'hot-springs'],
      common: ['Slugma', 'Numel', 'Magby', 'Torkoal', 'Rolycoly', 'Sizzlipede', 'Salandit', 'Houndour', 'Litleo', 'Heatmor', 'Geodude-Alola', 'Koffing'],
      rare: ['Chimchar', 'Gible', 'Growlithe-Hisui'],
    },
    'shelf': {
      name: 'Thunder Shelf',
      channels: ['storm-watch', 'shelf-gym', 'cliff-stairs', 'the-pylons'],
      types: ['Electric', 'Flying', 'Steel', 'Rock'],
      wild: ['storm-watch', 'cliff-stairs', 'the-pylons'],
      trainers: ['guitarist', 'scientist', 'birdkeeper', 'worker', 'hiker', 'acetrainerf'],
      common: ['Magnemite', 'Voltorb', 'Elekid', 'Joltik', 'Tynamo', 'Helioptile', 'Dedenne', 'Togedemaru', 'Pachirisu', 'Roggenrola', 'Rufflet', 'Skarmory'],
      rare: ['Voltorb-Hisui', 'Pichu', 'Morpeko'],
    },
    'cinder': {
      name: 'Cinder Row',
      channels: ['cinder-row', 'row-shop', 'the-jetty', 'cinder-ferry'],
      types: ['Fire', 'Water', 'Rock', 'Normal'],
      wild: ['cinder-row', 'the-jetty'],
      trainers: ['fisherman', 'sailor', 'firebreather', 'delinquent', 'youngster', 'worker'],
      noTrainers: ['row-shop'],
      common: ['Rattata', 'Houndour', 'Magikarp', 'Tentacool', 'Chewtle', 'Poochyena', 'Trubbish', 'Numel', 'Carvanha', 'Remoraid', 'Glameow', 'Yungoos'],
      rare: ['Charmander', 'Litten', 'Zigzagoon-Galar'],
    },

    // ----------------------------------------------------------------- Tsuki
    'shellstrand': {
      name: 'Shell Strand',
      channels: ['shell-strand', 'the-shell-line'],
      types: ['Water', 'Rock', 'Fairy', 'Flying'],
      wild: ['shell-strand', 'the-shell-line'],
      trainers: ['swimmerf', 'tuber', 'beauty', 'birdkeeper', 'picnicker', 'youngcouple'],
      common: ['Corsola', 'Staryu', 'Clamperl', 'Luvdisc', 'Shuckle', 'Carbink', 'Swablu', 'Bruxish', 'Alomomola', 'Wingull', 'Pikipek'],
      rare: ['Popplio', 'Tatsugiri', 'Minior', 'Omanyte'],
    },
    'moonpool': {
      name: 'Moon Pool',
      channels: ['moon-pool', 'the-night-water'],
      types: ['Water', 'Fairy', 'Psychic', 'Ice'],
      wild: ['moon-pool', 'the-night-water'],
      trainers: ['swimmerf', 'psychicf', 'beauty', 'lady', 'youngcouple'],
      common: ['Cleffa', 'Chinchou', 'Horsea', 'Mantyke', 'Frillish', 'Inkay', 'Hatenna', 'Smoochum', 'Slowpoke', 'Finneon', 'Azurill'],
      rare: ['Dratini', 'Lunatone', 'Munna'],
    },
    'hall': {
      name: "The Trainers' Hall",
      channels: ['trainers-hall', 'the-open-ladder', 'the-wall-of-names'],
      types: ['Fighting', 'Steel', 'Dark'],
      wild: [],
      trainers: ['acetrainer', 'acetrainerf', 'blackbelt', 'battlegirl', 'veteran', 'delinquent', 'ninjaboy'],
      common: ['Tyrogue', 'Riolu', 'Scraggy', 'Pawniard', 'Sneasel', 'Throh', 'Sawk', 'Crabrawler', 'Pancham', 'Meditite', 'Timburr', 'Makuhita'],
      rare: ['Farfetch’d-Galar', 'Falinks', 'Clobbopus'],
    },
    'driftwood': {
      name: 'Driftwood Cove',
      channels: ['driftwood-cove', 'the-tideline'],
      types: ['Water', 'Ground', 'Dark', 'Flying'],
      wild: ['driftwood-cove', 'the-tideline'],
      trainers: ['fisherman', 'sailor', 'backpacker', 'punk', 'abyssalgrunt'],
      common: ['Murkrow', 'Wingull', 'Tentacool', 'Sandile', 'Trubbish', 'Nickit', 'Shellos', 'Qwilfish', 'Cramorant', 'Remoraid', 'Drifloon'],
      rare: ['Dhelmise', 'Honedge', 'Klefki'],
    },
    'palmlands': {
      name: 'The Palmlands',
      channels: ['the-palmlands', 'the-green-middle'],
      types: ['Grass', 'Bug', 'Water', 'Flying'],
      wild: ['the-palmlands', 'the-green-middle'],
      trainers: ['bugcatcher', 'ranger', 'rangerf', 'picnicker', 'backpacker', 'birdkeeper'],
      common: ['Exeggcute', 'Tropius', 'Paras', 'Sewaddle', 'Pikipek', 'Oranguru', 'Ledyba', 'Surskit', 'Combee', 'Bounsweet', 'Cutiefly', 'Squawkabilly'],
      rare: ['Treecko', 'Goomy', 'Exeggutor-Alola', 'Oricorio-Pa\'u'],
    },
    'dunes': {
      name: 'Windward Dunes',
      channels: ['windward-dunes', 'the-dune-line'],
      types: ['Water', 'Ground', 'Flying', 'Dark'],
      wild: ['windward-dunes', 'the-dune-line'],
      trainers: ['acetrainer', 'acetrainerf', 'veteran', 'birdkeeper', 'backpacker', 'delinquent'],
      common: ['Sandile', 'Hippopotas', 'Sandygast', 'Cacnea', 'Maractus', 'Skorupi', 'Murkrow', 'Zorua', 'Arrokuda', 'Wailmer', 'Carvanha', 'Drilbur'],
      rare: ['Gible', 'Zorua-Hisui', 'Braviary-Hisui'],
    },
    'tidecall': {
      name: 'Tidecall Town',
      channels: ['the-stacks', 'tidecall-gym', 'poke-center-tsuki', 'tidecall-mart', 'the-causeway', 'stilt-houses', 'tidecall-ferry'],
      types: ['Rock', 'Water', 'Ground', 'Flying'],
      wild: ['the-stacks', 'the-causeway'],
      trainers: ['sailor', 'swimmer', 'fisherman', 'hiker', 'birdkeeper', 'tuber'],
      noTrainers: ['poke-center-tsuki', 'tidecall-mart', 'stilt-houses'],
      common: ['Binacle', 'Dwebble', 'Wingull', 'Krabby', 'Shellder', 'Staryu', 'Clauncher', 'Nacli', 'Klawf', 'Cramorant', 'Shellos', 'Chinchou'],
      rare: ['Kabuto', 'Lileep', 'Anorith', 'Relicanth'],
    },
    'grotto': {
      name: 'Moonlit Grotto',
      channels: ['grotto-mouth', 'deep-grotto', 'grotto-gym', 'the-tide-gate'],
      types: ['Dark', 'Water', 'Ghost', 'Poison'],
      wild: ['grotto-mouth', 'deep-grotto', 'the-tide-gate'],
      trainers: ['hexmaniac', 'punk', 'delinquent', 'swimmer', 'channeler', 'acetrainer'],
      common: ['Zubat', 'Frillish', 'Inkay', 'Skrelp', 'Mareanie', 'Carvanha', 'Qwilfish', 'Woobat', 'Gastly', 'Grimer', 'Shellder', 'Wimpod'],
      rare: ['Deino', 'Mimikyu', 'Sharpedo'],
    },
    'shoal': {
      name: 'Coral Shoal',
      channels: ['the-reef', 'drop-off', 'tide-pools', 'the-shallows'],
      types: ['Water', 'Ice', 'Psychic', 'Fairy'],
      wild: ['the-reef', 'drop-off', 'tide-pools', 'the-shallows'],
      trainers: ['swimmer', 'swimmerf', 'tuber', 'sailor', 'psychicf', 'beauty'],
      common: ['Corsola', 'Luvdisc', 'Clamperl', 'Horsea', 'Chinchou', 'Remoraid', 'Finizen', 'Alomomola', 'Bruxish', 'Pyukumuku', 'Spheal', 'Seel', 'Wailmer', 'Slowpoke'],
      rare: ['Dondozo', 'Veluza', 'Lapras'],
    },

    // ------------------------------------------------------- Strait crossings
    'watari': {
      name: 'Watari Bridge',
      channels: ['watari-bridge', 'the-toll-house', 'under-the-span', 'watari-ferry'],
      types: ['Water', 'Flying', 'Ghost'],
      wild: ['watari-bridge', 'under-the-span'],
      trainers: ['fisherman', 'cyclist', 'hiker', 'channeler', 'backpacker'],
      noTrainers: ['the-toll-house'],
      common: ['Magikarp', 'Remoraid', 'Finneon', 'Ducklett', 'Drifloon', 'Shuppet', 'Tentacool', 'Wingull', 'Horsea', 'Arrokuda', 'Gastly'],
      rare: ['Basculin-White-Striped', 'Spiritomb'],
    },
    'kakehashi': {
      name: 'Kakehashi Bridge',
      channels: ['kakehashi-bridge', 'the-north-tower', 'the-south-tower'],
      types: ['Flying', 'Steel', 'Water'],
      wild: ['kakehashi-bridge', 'the-north-tower', 'the-south-tower'],
      trainers: ['cyclist', 'worker', 'sailor', 'birdkeeper', 'acetrainer'],
      common: ['Skarmory', 'Rookidee', 'Starly', 'Fletchling', 'Ferroseed', 'Magnemite', 'Wingull', 'Wailmer', 'Mantyke', 'Tentacool', 'Swablu', 'Wattrel'],
      rare: ['Beldum', 'Archen', 'Flamigo'],
    },

    // -------------------------------------------------------------- Open sea
    'beacon': {
      name: 'Beacon Rock',
      channels: ['beacon-rock', 'beacon-ferry', 'the-light', 'keepers-room'],
      types: ['Water', 'Flying', 'Ice'],
      wild: ['beacon-rock', 'the-light'],
      trainers: ['sailor', 'swimmer', 'birdkeeper', 'fisherman'],
      noTrainers: ['keepers-room'],
      common: ['Wingull', 'Tentacool', 'Wailmer', 'Spheal', 'Seel', 'Delibird', 'Wattrel', 'Cramorant', 'Chinchou', 'Staryu', 'Horsea'],
      rare: ['Piplup', 'Lapras', 'Mantine'],
    },
    'aether': {
      name: 'Aether Paradise',
      channels: ['aether-dock', 'conservation-wing', 'labs', 'observation-deck', 'aether-labs'],
      types: ['Psychic', 'Steel', 'Fairy'],
      wild: ['aether-dock', 'conservation-wing'],
      trainers: ['scientist', 'worker', 'nurse', 'ranger', 'rangerf'],
      noTrainers: ['labs'],
      common: ['Bronzor', 'Klefki', 'Ralts', 'Mime Jr.', 'Cutiefly', 'Hatenna', 'Tinkatink', 'Espurr', 'Flabébé', 'Comfey', 'Elgyem', 'Solosis', 'Magnemite'],
      rare: ['Beldum', 'Porygon', 'Iron Valiant', 'Eevee'],
    },
    'bell': {
      name: 'The Sunken Bell',
      channels: ['sunken-bell', 'the-bell-chamber'],
      types: ['Water', 'Steel', 'Ghost', 'Dragon'],
      wild: ['sunken-bell', 'the-bell-chamber'],
      trainers: ['swimmer', 'swimmerf', 'channeler', 'sage', 'ruinmaniac'],
      common: ['Bronzor', 'Corsola-Galar', 'Frillish', 'Horsea', 'Skrelp', 'Chinchou', 'Honedge', 'Sandygast', 'Clauncher', 'Relicanth', 'Wimpod', 'Dhelmise'],
      rare: ['Dreepy', 'Flutter Mane', 'Kingdra'],
    },
    'abyss': {
      name: 'Abyss Headquarters',
      channels: ['the-anomaly', 'pressure-lock', 'abyssal-base', 'the-hatch', 'cold-corridor'],
      types: ['Water', 'Dark', 'Steel', 'Poison'],
      wild: ['the-anomaly', 'the-hatch'],
      trainers: ['abyssalgrunt', 'scientist', 'worker'],
      common: ['Carvanha', 'Qwilfish', 'Tentacool', 'Mareanie', 'Inkay', 'Wimpod', 'Chinchou', 'Grimer', 'Magnemite', 'Pawniard', 'Poochyena', 'Varoom'],
      rare: ['Nihilego', 'Iron Jugulis'],
    },

    // ------------------------------------------------------------ Kitaura
    // The north ferry's harbour below N's Castle: a cold coast.
    'kitaura': {
      name: 'Kitaura',
      channels: ['kitaura-harbour', 'kitaura-ferry', 'net-sheds', 'kitaura-inn'],
      types: ['Water', 'Ice', 'Flying', 'Normal'],
      wild: ['kitaura-harbour'],
      trainers: ['sailor', 'fisherman', 'worker', 'skier'],
      noTrainers: ['kitaura-inn'],
      common: ['Wingull', 'Spheal', 'Seel', 'Shellder', 'Krabby', 'Snorunt', 'Delibird', 'Cubchoo', 'Buizel', 'Arrokuda', 'Wattrel', 'Bergmite'],
      rare: ['Lapras', 'Eiscue'],
    },

    // ---------------------------------------------------------------- Tokoyo
    // The far isle with the gate, where crossovers arrive. What comes through the
    // portal is from somewhere else, which is the one story reason for Ultra Beasts.
    'tokoyo': {
      name: 'The Tokoyo Gate',
      channels: ['tokoyo-shore', 'tokoyo-ferry', 'the-far-gate', 'the-other-side'],
      types: ['Psychic', 'Ghost', 'Dragon', 'Fairy'],
      wild: ['tokoyo-shore', 'the-other-side'],
      trainers: ['psychic', 'psychicf', 'hexmaniac', 'sage', 'dragontamer', 'acetrainer'],
      noTrainers: ['the-far-gate'],
      common: ['Hatenna', 'Sinistea', 'Mimikyu', 'Espurr', 'Duskull', 'Litwick', 'Swablu', 'Clefairy', 'Dedenne', 'Elgyem', 'Drifloon', 'Spritzee'],
      rare: ['Poipole', 'Blacephalon', 'Stakataka'],
    },

    // ---------------------------------------------------------------- Routes
    'route-1': {
      name: 'Route 1',
      channels: ['route-1'],
      types: ['Normal', 'Bug', 'Flying'],
      wild: ['route-1'],
      trainers: ['youngster', 'lass', 'bugcatcher', 'schoolkid'],
      common: ['Rattata', 'Pidgey', 'Caterpie', 'Weedle', 'Zigzagoon', 'Patrat', 'Fletchling', 'Scatterbug', 'Lechonk', 'Tarountula', 'Wurmple', 'Yungoos'],
      rare: ['Pichu', 'Sprigatito', 'Spinda'],
    },
    'route-2': {
      name: 'Route 2',
      channels: ['route-2'],
      types: ['Normal', 'Bug', 'Grass'],
      wild: ['route-2'],
      trainers: ['youngster', 'lass', 'bugcatcher', 'camper', 'picnicker', 'worker'],
      common: ['Sentret', 'Oddish', 'Hoppip', 'Spinarak', 'Whismur', 'Seedot', 'Shroomish', 'Nincada', 'Burmy', 'Gossifleur', 'Bunnelby', 'Nymble', 'Smoliv', 'Budew'],
      rare: ['Chespin', 'Zangoose', 'Sudowoodo'],
    },
    'route-3': {
      name: 'Route 3',
      channels: ['route-3'],
      types: ['Flying', 'Normal', 'Water'],
      wild: ['route-3'],
      trainers: ['fisherman', 'sailor', 'birdkeeper', 'youngster', 'cyclist'],
      common: ['Spearow', 'Wingull', 'Psyduck', 'Magikarp', 'Tentacool', 'Doduo', 'Pidove', 'Taillow', 'Krabby', 'Buizel', 'Hoothoot', 'Meowth', 'Poliwag'],
      rare: ['Cramorant', 'Kangaskhan'],
    },
    'route-4': {
      name: 'Route 4',
      channels: ['route-4'],
      types: ['Ground', 'Flying', 'Water'],
      wild: ['route-4'],
      trainers: ['camper', 'picnicker', 'fisherman', 'backpacker', 'birdkeeper'],
      common: ['Sandshrew', 'Diglett', 'Wooper', 'Doduo', 'Krabby', 'Shellos', 'Mudbray', 'Silicobra', 'Wingull', 'Phanpy', 'Swablu', 'Tentacool'],
      rare: ['Dhelmise', 'Hippopotas'],
    },
    'route-5': {
      name: 'Route 5',
      channels: ['route-5'],
      types: ['Bug', 'Grass', 'Water'],
      wild: ['route-5'],
      trainers: ['bugcatcher', 'picnicker', 'camper', 'swimmerf', 'tuber', 'youngcouple'],
      common: ['Cherubi', 'Combee', 'Applin', 'Petilil', 'Hoppip', 'Lotad', 'Surskit', 'Volbeat', 'Illumise', 'Staryu', 'Wingull', 'Dewpider', 'Smoliv'],
      rare: ['Sobble', 'Heracross', 'Tropius'],
    },
    'route-6': {
      name: 'Route 6',
      channels: ['route-6'],
      types: ['Bug', 'Grass', 'Ghost'],
      wild: ['route-6'],
      trainers: ['bugcatcher', 'camper', 'channeler', 'hexmaniac', 'picnicker'],
      common: ['Weedle', 'Venonat', 'Paras', 'Shroomish', 'Pineco', 'Phantump', 'Pumpkaboo', 'Gastly', 'Sewaddle', 'Nincada', 'Morelull', 'Seedot', 'Spinarak'],
      rare: ['Grookey', 'Shedinja'],
    },
    'route-7': {
      name: 'Route 7',
      channels: ['route-7'],
      types: ['Rock', 'Psychic', 'Flying'],
      wild: ['route-7'],
      trainers: ['hiker', 'psychic', 'ruinmaniac', 'birdkeeper', 'backpacker'],
      common: ['Natu', 'Baltoy', 'Rockruff', 'Spoink', 'Girafarig', 'Drowzee', 'Abra', 'Roggenrola', 'Rufflet', 'Flittle', 'Spearow', 'Geodude'],
      rare: ['Sigilyph', 'Minior'],
    },
    'route-8': {
      name: 'Route 8',
      channels: ['route-8'],
      types: ['Bug', 'Grass', 'Water'],
      wild: ['route-8'],
      trainers: ['fisherman', 'camper', 'bugcatcher', 'hiker', 'ranger'],
      common: ['Poliwag', 'Goldeen', 'Yanma', 'Burmy', 'Karrablast', 'Shelmet', 'Snover', 'Deerling', 'Basculin', 'Barboach', 'Chewtle', 'Pineco'],
      rare: ['Froakie', 'Politoed'],
    },
    'route-9': {
      name: 'Route 9',
      channels: ['route-9'],
      types: ['Ice', 'Rock', 'Flying'],
      wild: ['route-9'],
      trainers: ['hiker', 'skier', 'birdkeeper', 'veteran', 'backpacker'],
      common: ['Snorunt', 'Swinub', 'Delibird', 'Vullaby', 'Cubchoo', 'Bergmite', 'Roggenrola', 'Rufflet', 'Cryogonal', 'Snom', 'Sandshrew-Alola', 'Aron'],
      rare: ['Bagon', 'Frigibax'],
    },
    'route-10': {
      name: 'Route 10',
      channels: ['route-10'],
      types: ['Fire', 'Ground', 'Rock'],
      wild: ['route-10'],
      trainers: ['firebreather', 'kindler', 'hiker', 'worker', 'backpacker'],
      common: ['Numel', 'Slugma', 'Diglett', 'Cubone', 'Trapinch', 'Rolycoly', 'Growlithe', 'Magby', 'Nacli', 'Dwebble', 'Ponyta', 'Hippopotas', 'Torkoal', 'Litleo'],
      rare: ['Charmander', 'Cyndaquil'],
    },
    'route-11': {
      name: 'Route 11',
      channels: ['route-11'],
      types: ['Rock', 'Electric', 'Fire'],
      wild: ['route-11'],
      trainers: ['hiker', 'guitarist', 'worker', 'firebreather', 'scientist'],
      common: ['Geodude-Alola', 'Roggenrola', 'Electrike', 'Shinx', 'Magby', 'Elekid', 'Nosepass', 'Rolycoly', 'Helioptile', 'Tadbulb', 'Litleo', 'Salandit'],
      rare: ['Jangmo-o', 'Rotom-Heat'],
    },
    'route-12': {
      name: 'Route 12',
      channels: ['route-12'],
      types: ['Water', 'Rock', 'Flying'],
      wild: ['route-12'],
      trainers: ['fisherman', 'sailor', 'hiker', 'birdkeeper', 'swimmer', 'abyssalgrunt'],
      common: ['Wingull', 'Tentacool', 'Binacle', 'Corphish', 'Clauncher', 'Wimpod', 'Staryu', 'Spearow', 'Carvanha', 'Remoraid', 'Bombirdier', 'Roggenrola'],
      rare: ['Tirtouga', 'Archen', 'Skarmory'],
    },
    'route-13': {
      name: 'Route 13',
      channels: ['route-13'],
      types: ['Water', 'Rock', 'Poison'],
      wild: ['route-13'],
      trainers: ['swimmer', 'fisherman', 'hexmaniac', 'punk', 'sailor', 'tuber'],
      common: ['Tentacool', 'Mareanie', 'Skrelp', 'Qwilfish', 'Binacle', 'Krabby', 'Grimer', 'Staryu', 'Shellos', 'Clauncher', 'Chinchou'],
      rare: ['Omanyte', 'Toxapex', 'Pincurchin'],
    },
    'route-14': {
      name: 'Route 14',
      channels: ['route-14'],
      types: ['Flying', 'Water', 'Rock'],
      wild: ['route-14'],
      trainers: ['birdkeeper', 'sailor', 'fisherman', 'hiker', 'cyclist', 'youngcouple'],
      common: ['Wingull', 'Wattrel', 'Swablu', 'Pidgey', 'Tentacool', 'Wailmer', 'Rookidee', 'Nacli', 'Binacle', 'Roggenrola', 'Taillow', 'Doduo'],
      rare: ['Piplup', 'Aerodactyl', 'Flamigo'],
    },
  },
};
