'use strict';
/**
 * Sinnoh encounter tables.
 *
 * Built by tools/build-sinnoh-encounters.js from the atlas region file, so the
 * channels here are exactly the channels on the map. Do not edit by hand: edit
 * the builder and run it again.
 *
 * Same shape as kagura.js, and the same rule - the region comes first but is
 * not a fence. `common` is Sinnoh's own, `rare` is where the rest of the world
 * turns up, so every Pokemon can be met somewhere without the place stopping
 * feeling like Sinnoh. No legendaries and no mythicals, as in Kagura: Dialga on
 * the Spear Pillar and Giratina behind Turnback Cave are story that staff run,
 * not a wild roll.
 */
module.exports = {
  region: 'sinnoh',
  locations: {
    'twinleaf': {
      name: 'Twinleaf Town',
      channels: ['twinleaf-town', 'your-house', 'rivals-house', 'twinleaf-path'],
      types: ['Normal', 'Bug', 'Flying'],
      wild: ['twinleaf-town', 'twinleaf-path'],
      trainers: ['youngster', 'lass', 'schoolkid'],
      noTrainers: ['your-house', 'rivals-house'],
      common: ['Bidoof', 'Starly', 'Kricketot', 'Zigzagoon', 'Wurmple', 'Bunnelby'],
      rare: ['Eevee', 'Munchlax', 'Riolu'],
    },
    'lakeverity': {
      name: 'Lake Verity',
      channels: ['lake-verity', 'verity-cavern'],
      types: ['Water', 'Bug', 'Normal'],
      wild: ['lake-verity', 'verity-cavern'],
      trainers: ['fisherman', 'swimmer', 'picnicker'],
      noTrainers: [],
      common: ['Psyduck', 'Magikarp', 'Marill', 'Starly', 'Bidoof', 'Wooper'],
      rare: ['Chingling', 'Ralts', 'Feebas'],
    },
    'sandgem': {
      name: 'Sandgem Town',
      channels: ['sandgem-town', 'rowans-lab', 'sandgem-beach', 'sandgem-mart', 'sandgem-centre'],
      types: ['Normal', 'Water', 'Flying', 'Bug'],
      wild: ['sandgem-town', 'sandgem-beach'],
      trainers: ['youngster', 'lass', 'fisherman', 'schoolkid'],
      noTrainers: ['rowans-lab', 'sandgem-mart', 'sandgem-centre'],
      common: ['Bidoof', 'Starly', 'Shellos', 'Wingull', 'Krabby', 'Magikarp'],
      rare: ['Eevee', 'Clamperl', 'Tentacool'],
    },
    'palpark': {
      name: 'Pal Park',
      channels: ['pal-park', 'the-enclosures'],
      types: ['Normal', 'Grass', 'Water', 'Bug'],
      wild: ['pal-park', 'the-enclosures'],
      trainers: ['ranger', 'rangerf', 'breeder', 'pokefan'],
      noTrainers: [],
      common: ['Bibarel', 'Girafarig', 'Stantler', 'Sudowoodo', 'Miltank', 'Bidoof'],
      rare: ['Tropius', 'Bouffalant', 'Dunsparce'],
    },
    'jubilife': {
      name: 'Jubilife City',
      channels: ['jubilife-city', 'jubilife-tv', 'global-trade', 'poketch-co', 'trainers-school', 'jubilife-centre', 'jubilife-mart'],
      types: ['Normal', 'Flying', 'Electric'],
      wild: ['jubilife-city'],
      trainers: ['worker', 'gentleman', 'policeman', 'schoolkid', 'guitarist', 'richboy'],
      noTrainers: ['jubilife-tv', 'global-trade', 'poketch-co', 'trainers-school', 'jubilife-centre', 'jubilife-mart'],
      common: ['Rattata', 'Zigzagoon', 'Meowth', 'Magnemite', 'Voltorb', 'Pidove', 'Glameow'],
      rare: ['Rotom', 'Porygon', 'Varoom'],
    },
    'ravagedpath': {
      name: 'Ravaged Path',
      channels: ['ravaged-path'],
      types: ['Water', 'Rock', 'Normal'],
      wild: ['ravaged-path'],
      trainers: ['hiker', 'camper', 'fisherman'],
      noTrainers: [],
      common: ['Zubat', 'Psyduck', 'Geodude', 'Wooper', 'Bidoof'],
      rare: ['Barboach', 'Woobat'],
    },
    'canalave': {
      name: 'Canalave City',
      channels: ['canalave-city', 'canalave-gym', 'canalave-library', 'the-drawbridge', 'canalave-docks', 'canalave-centre', 'sailors-berth'],
      types: ['Steel', 'Water', 'Flying'],
      wild: ['canalave-city', 'canalave-gym', 'the-drawbridge', 'canalave-docks'],
      trainers: ['sailor', 'worker', 'fisherman', 'scientist', 'blackbelt'],
      noTrainers: ['canalave-library', 'canalave-centre', 'sailors-berth'],
      common: ['Magikarp', 'Tentacool', 'Wingull', 'Magnemite', 'Bronzor', 'Klink', 'Skarmory'],
      rare: ['Beldum', 'Riolu', 'Togedemaru'],
    },
    'ironisland': {
      name: 'Iron Island',
      channels: ['iron-island', 'the-shafts', 'lower-levels'],
      types: ['Steel', 'Rock', 'Ground', 'Fighting'],
      wild: ['iron-island', 'the-shafts', 'lower-levels'],
      trainers: ['hiker', 'worker', 'blackbelt', 'ruinmaniac'],
      noTrainers: [],
      common: ['Geodude', 'Onix', 'Machop', 'Zubat', 'Bronzor', 'Aron', 'Magnemite'],
      rare: ['Riolu', 'Beldum', 'Larvitar'],
    },
    'fullmoon': {
      name: 'Fullmoon Island',
      channels: ['fullmoon-island', 'the-clearing'],
      types: ['Psychic', 'Fairy', 'Flying'],
      wild: ['fullmoon-island', 'the-clearing'],
      trainers: ['psychic', 'psychicf', 'sage'],
      noTrainers: [],
      common: ['Clefairy', 'Munna', 'Drifloon', 'Hoothoot', 'Swablu'],
      rare: ['Ralts', 'Cutiefly', 'Sinistea'],
    },
    'newmoon': {
      name: 'Newmoon Island',
      channels: ['newmoon-island', 'the-dead-grove'],
      types: ['Dark', 'Ghost'],
      wild: ['newmoon-island', 'the-dead-grove'],
      trainers: ['hexmaniac', 'channeler', 'delinquent'],
      noTrainers: [],
      common: ['Sableye', 'Murkrow', 'Gastly', 'Houndour', 'Spiritomb'],
      rare: ['Absol', 'Zorua', 'Impidimp'],
    },
    'oreburghgate': {
      name: 'Oreburgh Gate',
      channels: ['oreburgh-gate', 'gate-lower-level'],
      types: ['Rock', 'Ground', 'Zubat', 'Water'],
      wild: ['oreburgh-gate', 'gate-lower-level'],
      trainers: ['hiker', 'camper', 'blackbelt'],
      noTrainers: [],
      common: ['Zubat', 'Geodude', 'Psyduck', 'Machop', 'Onix'],
      rare: ['Gible', 'Nosepass'],
    },
    'oreburgh': {
      name: 'Oreburgh City',
      channels: ['oreburgh-city', 'oreburgh-gym', 'oreburgh-mine', 'mining-museum', 'oreburgh-centre', 'oreburgh-mart'],
      types: ['Rock', 'Ground', 'Steel', 'Fire'],
      wild: ['oreburgh-city', 'oreburgh-gym', 'oreburgh-mine'],
      trainers: ['hiker', 'worker', 'ruinmaniac', 'blackbelt', 'scientist'],
      noTrainers: ['mining-museum', 'oreburgh-centre', 'oreburgh-mart'],
      common: ['Geodude', 'Onix', 'Machop', 'Aron', 'Roggenrola', 'Nosepass', 'Cranidos', 'Shieldon'],
      rare: ['Gible', 'Larvitar', 'Rolycoly'],
    },
    'waywardcave': {
      name: 'Wayward Cave',
      channels: ['wayward-cave', 'wayward-lower'],
      types: ['Ground', 'Rock', 'Steel'],
      wild: ['wayward-cave', 'wayward-lower'],
      trainers: ['hiker', 'cyclist', 'ruinmaniac'],
      noTrainers: [],
      common: ['Zubat', 'Geodude', 'Bronzor', 'Onix', 'Gible'],
      rare: ['Gabite', 'Carbink'],
    },
    'floaroma': {
      name: 'Floaroma Town',
      channels: ['floaroma-town', 'floaroma-meadow', 'flower-shop', 'honey-stalls'],
      types: ['Grass', 'Bug', 'Fairy', 'Flying'],
      wild: ['floaroma-town', 'floaroma-meadow', 'honey-stalls'],
      trainers: ['picnicker', 'beauty', 'breeder', 'lady'],
      noTrainers: ['flower-shop'],
      common: ['Budew', 'Combee', 'Cherubi', 'Roselia', 'Beautifly', 'Dustox', 'Petilil'],
      rare: ['Cherrim', 'Comfey', 'Flabebe'],
    },
    'windworks': {
      name: 'Valley Windworks',
      channels: ['valley-windworks', 'the-turbine-hall'],
      types: ['Electric', 'Normal', 'Flying'],
      wild: ['valley-windworks', 'the-turbine-hall'],
      trainers: ['galacticgrunt', 'scientist', 'worker'],
      noTrainers: [],
      common: ['Magnemite', 'Voltorb', 'Electabuzz', 'Pachirisu', 'Shinx', 'Klink'],
      rare: ['Rotom', 'Elekid', 'Tadbulb'],
    },
    'fuego': {
      name: 'Fuego Ironworks',
      channels: ['fuego-ironworks', 'the-furnace-floor'],
      types: ['Fire', 'Steel', 'Bug'],
      wild: ['fuego-ironworks', 'the-furnace-floor'],
      trainers: ['kindler', 'firebreather', 'worker'],
      noTrainers: [],
      common: ['Magmar', 'Slugma', 'Numel', 'Magnemite', 'Klink', 'Torkoal'],
      rare: ['Magby', 'Rotom-Heat', 'Charcadet'],
    },
    'eternaforest': {
      name: 'Eterna Forest',
      channels: ['eterna-forest', 'forest-path'],
      types: ['Bug', 'Grass', 'Poison', 'Psychic'],
      wild: ['eterna-forest', 'forest-path'],
      trainers: ['bugcatcher', 'camper', 'picnicker', 'hexmaniac'],
      noTrainers: [],
      common: ['Wurmple', 'Silcoon', 'Cascoon', 'Budew', 'Buneary', 'Hoothoot', 'Murkrow', 'Bidoof'],
      rare: ['Chingling', 'Eevee', 'Sewaddle'],
    },
    'chateau': {
      name: 'The Old Chateau',
      channels: ['the-old-chateau', 'chateau-hall', 'the-far-bedroom'],
      types: ['Ghost', 'Poison', 'Normal'],
      wild: ['the-old-chateau', 'chateau-hall', 'the-far-bedroom'],
      trainers: ['hexmaniac', 'channeler', 'psychicf'],
      noTrainers: [],
      common: ['Gastly', 'Haunter', 'Drifloon', 'Duskull', 'Mismagius', 'Murkrow'],
      rare: ['Rotom', 'Spiritomb', 'Sinistea'],
    },
    'eterna': {
      name: 'Eterna City',
      channels: ['eterna-city', 'eterna-gym', 'the-statue', 'cycle-shop', 'galactic-eterna', 'eterna-centre', 'eterna-mart'],
      types: ['Grass', 'Bug', 'Poison', 'Psychic'],
      wild: ['eterna-city', 'eterna-gym', 'the-statue', 'galactic-eterna'],
      trainers: ['bugcatcher', 'cyclist', 'breeder', 'galacticgrunt', 'ruinmaniac'],
      noTrainers: ['cycle-shop', 'eterna-centre', 'eterna-mart'],
      common: ['Budew', 'Roselia', 'Kricketot', 'Combee', 'Cherubi', 'Wurmple'],
      rare: ['Turtwig', 'Sunkern', 'Bramblin'],
    },
    'coronet': {
      name: 'Mt. Coronet',
      channels: ['mt-coronet', 'coronet-lower', 'the-summit-path'],
      types: ['Rock', 'Ground', 'Steel', 'Ice', 'Psychic'],
      wild: ['mt-coronet', 'coronet-lower', 'the-summit-path'],
      trainers: ['hiker', 'blackbelt', 'psychic', 'veteran', 'ruinmaniac'],
      noTrainers: [],
      common: ['Zubat', 'Golbat', 'Geodude', 'Graveler', 'Machop', 'Machoke', 'Bronzor', 'Nosepass', 'Chingling', 'Meditite', 'Clefairy'],
      rare: ['Bagon', 'Beldum', 'Absol'],
    },
    'hearthome': {
      name: 'Hearthome City',
      channels: ['hearthome-city', 'hearthome-gym', 'contest-hall', 'amity-square', 'the-foreign-building', 'hearthome-centre', 'hearthome-mart'],
      types: ['Ghost', 'Normal', 'Psychic', 'Fairy'],
      wild: ['hearthome-city', 'hearthome-gym'],
      trainers: ['beauty', 'artist', 'lady', 'acetrainerf', 'kimonogirl'],
      noTrainers: ['contest-hall', 'amity-square', 'the-foreign-building', 'hearthome-centre', 'hearthome-mart'],
      common: ['Glameow', 'Buneary', 'Drifloon', 'Duskull', 'Chingling', 'Ralts', 'Kirlia', 'Mime Jr.'],
      rare: ['Gothita', 'Espurr', 'Milcery'],
    },
    'losttower': {
      name: 'Lost Tower',
      channels: ['lost-tower', 'the-top-floor'],
      types: ['Ghost', 'Normal', 'Flying'],
      wild: ['lost-tower', 'the-top-floor'],
      trainers: ['channeler', 'hexmaniac', 'sage'],
      noTrainers: [],
      common: ['Gastly', 'Haunter', 'Duskull', 'Murkrow', 'Zubat', 'Golbat'],
      rare: ['Misdreavus', 'Yamask', 'Greavard'],
    },
    'solaceon': {
      name: 'Solaceon Town',
      channels: ['solaceon-town', 'solaceon-day-care', 'news-press', 'solaceon-centre'],
      types: ['Normal', 'Ground', 'Psychic'],
      wild: ['solaceon-town'],
      trainers: ['breeder', 'pokefan', 'ruinmaniac', 'schoolkid'],
      noTrainers: ['solaceon-day-care', 'news-press', 'solaceon-centre'],
      common: ['Bidoof', 'Bibarel', 'Kricketot', 'Chansey', 'Hoothoot', 'Ponyta'],
      rare: ['Happiny', 'Togepi', 'Dunsparce'],
    },
    'solaceonruins': {
      name: 'Solaceon Ruins',
      channels: ['solaceon-ruins', 'the-written-chambers'],
      types: ['Psychic'],
      wild: ['solaceon-ruins', 'the-written-chambers'],
      trainers: ['ruinmaniac', 'psychic', 'hexmaniac'],
      noTrainers: [],
      common: ['Unown', 'Geodude', 'Zubat', 'Bronzor'],
      rare: ['Sigilyph', 'Baltoy', 'Klawf'],
    },
    'veilstone': {
      name: 'Veilstone City',
      channels: ['veilstone-city', 'veilstone-gym', 'department-store', 'game-corner', 'galactic-hq', 'the-meteorites', 'veilstone-centre'],
      types: ['Fighting', 'Rock', 'Steel', 'Normal'],
      wild: ['veilstone-city', 'veilstone-gym', 'department-store', 'game-corner', 'galactic-hq', 'the-meteorites'],
      trainers: ['blackbelt', 'battlegirl', 'galacticgrunt', 'punk', 'delinquent'],
      noTrainers: ['veilstone-centre'],
      common: ['Machop', 'Meditite', 'Stunky', 'Bronzor', 'Croagunk', 'Makuhita'],
      rare: ['Riolu', 'Mienfoo', 'Falinks'],
    },
    'pastoria': {
      name: 'Pastoria City',
      channels: ['pastoria-city', 'pastoria-gym', 'croagunk-festival', 'pastoria-centre', 'pastoria-mart'],
      types: ['Water', 'Poison', 'Bug', 'Ground'],
      wild: ['pastoria-city', 'pastoria-gym', 'croagunk-festival'],
      trainers: ['fisherman', 'swimmer', 'ranger', 'tuber'],
      noTrainers: ['pastoria-centre', 'pastoria-mart'],
      common: ['Croagunk', 'Wooper', 'Quagsire', 'Marill', 'Psyduck', 'Shellos', 'Barboach'],
      rare: ['Toxicroak', 'Gastrodon', 'Tympole'],
    },
    'greatmarsh': {
      name: 'The Great Marsh',
      channels: ['the-great-marsh', 'marsh-tram', 'observation-tower'],
      types: ['Water', 'Bug', 'Poison', 'Ground', 'Flying'],
      wild: ['the-great-marsh', 'marsh-tram', 'observation-tower'],
      trainers: ['ranger', 'rangerf', 'bugcatcher', 'pokefan'],
      noTrainers: [],
      common: ['Croagunk', 'Quagsire', 'Wooper', 'Bidoof', 'Barboach', 'Skorupi', 'Tangela', 'Yanma', 'Kecleon', 'Tropius'],
      rare: ['Carnivine', 'Politoed', 'Shroomish'],
    },
    'valorlakefront': {
      name: 'Valor Lakefront',
      channels: ['valor-lakefront', 'hotel-grand-lake', 'seven-stars', 'lakefront-road'],
      types: ['Water', 'Normal', 'Flying'],
      wild: ['valor-lakefront', 'hotel-grand-lake', 'seven-stars', 'lakefront-road'],
      trainers: ['tuber', 'beauty', 'richboy', 'acetrainer'],
      noTrainers: [],
      common: ['Staravia', 'Bibarel', 'Shellos', 'Buizel', 'Wingull', 'Glameow'],
      rare: ['Finneon', 'Lumineon', 'Chatot'],
    },
    'lakevalor': {
      name: 'Lake Valor',
      channels: ['lake-valor', 'valor-cavern'],
      types: ['Water', 'Psychic', 'Normal'],
      wild: ['lake-valor', 'valor-cavern'],
      trainers: ['fisherman', 'swimmer', 'swimmerf', 'galacticgrunt'],
      noTrainers: [],
      common: ['Psyduck', 'Golduck', 'Magikarp', 'Gyarados', 'Marill', 'Buizel', 'Barboach'],
      rare: ['Chingling', 'Feebas', 'Dratini'],
    },
    'sendoff': {
      name: 'Sendoff Spring',
      channels: ['sendoff-spring', 'the-still-pool'],
      types: ['Water', 'Ghost', 'Dark'],
      wild: ['sendoff-spring', 'the-still-pool'],
      trainers: ['veteran', 'hexmaniac', 'psychic'],
      noTrainers: [],
      common: ['Golduck', 'Dusclops', 'Mismagius', 'Gastly', 'Sableye', 'Drifblim'],
      rare: ['Spiritomb', 'Duskull', 'Sandygast'],
    },
    'turnback': {
      name: 'Turnback Cave',
      channels: ['turnback-cave', 'the-three-pillars'],
      types: ['Ghost', 'Dark', 'Dragon'],
      wild: ['turnback-cave', 'the-three-pillars'],
      trainers: ['veteran', 'hexmaniac', 'channeler'],
      noTrainers: [],
      common: ['Duskull', 'Dusclops', 'Gastly', 'Haunter', 'Sableye', 'Spiritomb', 'Golbat'],
      rare: ['Drifblim', 'Absol', 'Dreepy'],
    },
    'sunyshore': {
      name: 'Sunyshore City',
      channels: ['sunyshore-city', 'sunyshore-gym', 'vista-lighthouse', 'the-walkways', 'sunyshore-market', 'sunyshore-centre'],
      types: ['Electric', 'Water', 'Flying', 'Steel'],
      wild: ['sunyshore-city', 'sunyshore-gym', 'the-walkways', 'sunyshore-market'],
      trainers: ['sailor', 'guitarist', 'scientist', 'acetrainer', 'swimmer'],
      noTrainers: ['vista-lighthouse', 'sunyshore-centre'],
      common: ['Pikachu', 'Magnemite', 'Voltorb', 'Electabuzz', 'Pachirisu', 'Chinchou', 'Wingull'],
      rare: ['Rotom', 'Tynamo', 'Pawmi'],
    },
    'celestic': {
      name: 'Celestic Town',
      channels: ['celestic-town', 'celestic-ruins', 'the-shrine', 'grandmothers-house'],
      types: ['Rock', 'Ground', 'Psychic', 'Flying'],
      wild: ['celestic-town', 'celestic-ruins', 'the-shrine'],
      trainers: ['sage', 'ruinmaniac', 'psychicf', 'gentleman'],
      noTrainers: ['grandmothers-house'],
      common: ['Bidoof', 'Bibarel', 'Hoothoot', 'Noctowl', 'Chingling', 'Bronzor', 'Geodude'],
      rare: ['Sigilyph', 'Unown', 'Munna'],
    },
    'spearpillar': {
      name: 'Spear Pillar',
      channels: ['spear-pillar', 'the-pillars'],
      types: ['Dragon', 'Steel', 'Psychic', 'Ice'],
      wild: ['spear-pillar', 'the-pillars'],
      trainers: ['veteran', 'acetrainer', 'psychic', 'galacticgrunt'],
      noTrainers: [],
      common: ['Golbat', 'Machoke', 'Bronzong', 'Absol', 'Sneasel', 'Medicham', 'Clefairy'],
      rare: ['Bagon', 'Beldum', 'Deino'],
    },
    'distortion': {
      name: 'The Distortion World',
      channels: ['the-distortion-world', 'broken-ground'],
      types: ['Ghost', 'Dragon', 'Dark'],
      wild: ['the-distortion-world', 'broken-ground'],
      trainers: ['hexmaniac', 'veteran', 'channeler'],
      noTrainers: [],
      common: ['Gastly', 'Haunter', 'Duskull', 'Drifblim', 'Sableye', 'Mismagius', 'Spiritomb'],
      rare: ['Dusknoir', 'Chandelure', 'Dreepy'],
    },
    'lakeacuity': {
      name: 'Lake Acuity',
      channels: ['lake-acuity', 'acuity-cavern'],
      types: ['Ice', 'Water', 'Psychic'],
      wild: ['lake-acuity', 'acuity-cavern'],
      trainers: ['skier', 'swimmer', 'galacticgrunt'],
      noTrainers: [],
      common: ['Snover', 'Sneasel', 'Snorunt', 'Swinub', 'Magikarp', 'Golduck'],
      rare: ['Froslass', 'Chingling', 'Cubchoo'],
    },
    'snowpoint': {
      name: 'Snowpoint City',
      channels: ['snowpoint-city', 'snowpoint-gym', 'snowpoint-harbour', 'snowpoint-centre', 'snowpoint-mart'],
      types: ['Ice', 'Steel', 'Normal', 'Flying'],
      wild: ['snowpoint-city', 'snowpoint-gym', 'snowpoint-harbour'],
      trainers: ['skier', 'blackbelt', 'veteran', 'sage'],
      noTrainers: ['snowpoint-centre', 'snowpoint-mart'],
      common: ['Snover', 'Sneasel', 'Snorunt', 'Swinub', 'Zubat', 'Glalie', 'Delibird'],
      rare: ['Weavile', 'Cubchoo', 'Frigibax'],
    },
    'snowpointtemple': {
      name: 'Snowpoint Temple',
      channels: ['snowpoint-temple', 'the-bottom-floor'],
      types: ['Ice', 'Rock', 'Steel'],
      wild: ['snowpoint-temple', 'the-bottom-floor'],
      trainers: ['sage', 'ruinmaniac', 'veteran'],
      noTrainers: [],
      common: ['Snorunt', 'Glalie', 'Sneasel', 'Golbat', 'Bronzor', 'Nosepass'],
      rare: ['Froslass', 'Beldum', 'Bergmite'],
    },
    'sinnohvictory': {
      name: 'Victory Road',
      channels: ['victory-road-sinnoh', 'the-waterfall-level', 'the-last-climb'],
      types: ['Rock', 'Ground', 'Fighting', 'Dragon', 'Steel'],
      wild: ['the-waterfall-level', 'the-last-climb'],
      trainers: ['veteran', 'acetrainer', 'acetrainerf', 'blackbelt', 'dragontamer'],
      noTrainers: ['victory-road-sinnoh'],
      common: ['Golbat', 'Graveler', 'Machoke', 'Steelix', 'Rhyhorn', 'Onix', 'Gabite', 'Floatzel'],
      rare: ['Gible', 'Larvitar', 'Bagon'],
    },
    'sinnohleague': {
      name: 'Sinnoh League',
      channels: ['league-gate', 'sinnoh-league-centre', 'sinnoh-league-mart', 'hall-of-aaron', 'hall-of-bertha', 'hall-of-flint', 'hall-of-lucian', 'champions-room', 'sinnoh-hall-of-fame'],
      types: [],
      wild: [],
      trainers: [],
      noTrainers: ['league-gate', 'sinnoh-league-centre', 'sinnoh-league-mart', 'hall-of-aaron', 'hall-of-bertha', 'hall-of-flint', 'hall-of-lucian', 'champions-room', 'sinnoh-hall-of-fame'],
      common: [],
      rare: [],
    },
    'flowerparadise': {
      name: 'Flower Paradise',
      channels: ['flower-paradise', 'seabreak-path'],
      types: ['Grass', 'Fairy', 'Flying'],
      wild: ['flower-paradise', 'seabreak-path'],
      trainers: ['beauty', 'lady', 'breeder'],
      noTrainers: [],
      common: ['Roselia', 'Cherubi', 'Cherrim', 'Combee', 'Vespiquen', 'Petilil'],
      rare: ['Comfey', 'Flabebe', 'Sunflora'],
    },
    'battlefrontier': {
      name: 'Battle Frontier',
      channels: ['battle-frontier', 'battle-tower', 'battle-factory', 'battle-hall', 'battle-castle', 'battle-arcade'],
      types: [],
      wild: [],
      trainers: [],
      noTrainers: [],
      common: [],
      rare: [],
    },
    'fightarea': {
      name: 'Fight Area',
      channels: ['fight-area', 'the-landing', 'fight-area-centre', 'fight-area-mart'],
      types: ['Fighting', 'Normal', 'Flying', 'Fire'],
      wild: ['fight-area', 'the-landing'],
      trainers: ['blackbelt', 'battlegirl', 'veteran', 'acetrainer'],
      noTrainers: ['fight-area-centre', 'fight-area-mart'],
      common: ['Machoke', 'Rhyhorn', 'Magmar', 'Staraptor', 'Kricketune', 'Makuhita'],
      rare: ['Hitmonlee', 'Hitmonchan', 'Pawniard'],
    },
    'survivalarea': {
      name: 'Survival Area',
      channels: ['survival-area', 'survival-centre', 'the-227-road'],
      types: ['Fighting', 'Ground', 'Fire', 'Rock'],
      wild: ['survival-area', 'the-227-road'],
      trainers: ['blackbelt', 'hiker', 'veteran', 'kindler'],
      noTrainers: ['survival-centre'],
      common: ['Machoke', 'Rhyhorn', 'Magmar', 'Graveler', 'Numel', 'Camerupt'],
      rare: ['Hitmontop', 'Riolu', 'Toxel'],
    },
    'resortarea': {
      name: 'Resort Area',
      channels: ['resort-area', 'the-villa', 'the-hot-spring', 'ribbon-syndicate'],
      types: ['Water', 'Normal', 'Flying'],
      wild: ['resort-area'],
      trainers: ['richboy', 'lady', 'beauty', 'veteran', 'swimmerf'],
      noTrainers: ['the-villa', 'the-hot-spring', 'ribbon-syndicate'],
      common: ['Wingull', 'Pelipper', 'Staravia', 'Bibarel', 'Chansey', 'Miltank'],
      rare: ['Tropius', 'Chatot', 'Alcremie'],
    },
    'starkmountain': {
      name: 'Stark Mountain',
      channels: ['stark-mountain', 'the-inner-chamber'],
      types: ['Fire', 'Rock', 'Ground', 'Steel'],
      wild: ['stark-mountain'],
      trainers: ['kindler', 'firebreather', 'veteran', 'hiker'],
      noTrainers: ['the-inner-chamber'],
      common: ['Magmar', 'Slugma', 'Magcargo', 'Numel', 'Camerupt', 'Rhyhorn', 'Graveler', 'Torkoal'],
      rare: ['Magby', 'Larvitar', 'Charcadet'],
    },
    'route-201': {
      name: 'Route 201',
      channels: ['route-201'],
      types: ['Normal', 'Bug', 'Flying'],
      wild: ['route-201'],
      trainers: ['youngster', 'lass'],
      noTrainers: [],
      common: ['Starly', 'Bidoof', 'Kricketot'],
      rare: ['Shinx', 'Buneary'],
    },
    'route-202': {
      name: 'Route 202',
      channels: ['route-202'],
      types: ['Normal', 'Bug', 'Flying', 'Electric'],
      wild: ['route-202'],
      trainers: ['youngster', 'lass', 'schoolkid'],
      noTrainers: [],
      common: ['Starly', 'Bidoof', 'Shinx', 'Kricketot'],
      rare: ['Buneary', 'Pachirisu'],
    },
    'route-203': {
      name: 'Route 203',
      channels: ['route-203'],
      types: ['Normal', 'Flying', 'Fighting'],
      wild: ['route-203'],
      trainers: ['youngster', 'bugcatcher', 'lass', 'schoolkid'],
      noTrainers: [],
      common: ['Starly', 'Bidoof', 'Shinx', 'Abra', 'Zubat'],
      rare: ['Machop', 'Ralts'],
    },
    'route-204': {
      name: 'Route 204',
      channels: ['route-204'],
      types: ['Normal', 'Bug', 'Grass', 'Water'],
      wild: ['route-204'],
      trainers: ['bugcatcher', 'picnicker', 'camper'],
      noTrainers: [],
      common: ['Starly', 'Bidoof', 'Shinx', 'Budew', 'Wurmple', 'Kricketot'],
      rare: ['Burmy', 'Combee'],
    },
    'route-205': {
      name: 'Route 205',
      channels: ['route-205'],
      types: ['Bug', 'Grass', 'Water', 'Fire'],
      wild: ['route-205'],
      trainers: ['bugcatcher', 'fisherman', 'camper', 'galacticgrunt'],
      noTrainers: [],
      common: ['Bidoof', 'Buizel', 'Shellos', 'Wurmple', 'Silcoon', 'Cascoon'],
      rare: ['Pachirisu', 'Chatot'],
    },
    'route-206': {
      name: 'Cycling Road',
      channels: ['route-206'],
      types: ['Normal', 'Flying', 'Ground'],
      wild: ['route-206'],
      trainers: ['cyclist', 'hiker', 'camper', 'picnicker'],
      noTrainers: [],
      common: ['Geodude', 'Machop', 'Ponyta', 'Gligar', 'Kricketune', 'Stunky'],
      rare: ['Gible', 'Bronzor'],
    },
    'route-207': {
      name: 'Route 207',
      channels: ['route-207'],
      types: ['Ground', 'Rock', 'Normal'],
      wild: ['route-207'],
      trainers: ['hiker', 'camper', 'ruinmaniac'],
      noTrainers: [],
      common: ['Geodude', 'Machop', 'Ponyta', 'Kricketune', 'Bronzor'],
      rare: ['Gligar', 'Nosepass'],
    },
    'route-208': {
      name: 'Route 208',
      channels: ['route-208'],
      types: ['Normal', 'Water', 'Bug'],
      wild: ['route-208'],
      trainers: ['fisherman', 'breeder', 'schoolkid', 'picnicker'],
      noTrainers: [],
      common: ['Bidoof', 'Bibarel', 'Psyduck', 'Machop', 'Roselia'],
      rare: ['Chansey', 'Feebas'],
    },
    'route-209': {
      name: 'Route 209',
      channels: ['route-209'],
      types: ['Normal', 'Flying', 'Ghost', 'Water'],
      wild: ['route-209'],
      trainers: ['schoolkid', 'lass', 'hexmaniac', 'breeder', 'ruinmaniac'],
      noTrainers: [],
      common: ['Staravia', 'Bibarel', 'Psyduck', 'Roselia', 'Ralts', 'Bronzor'],
      rare: ['Chansey', 'Happiny'],
    },
    'route-210': {
      name: 'Route 210',
      channels: ['route-210'],
      types: ['Normal', 'Grass', 'Flying', 'Ground'],
      wild: ['route-210'],
      trainers: ['camper', 'picnicker', 'breeder', 'sage'],
      noTrainers: [],
      common: ['Ponyta', 'Machoke', 'Meditite', 'Bibarel', 'Noctowl', 'Hoothoot'],
      rare: ['Chansey', 'Stantler'],
    },
    'route-211': {
      name: 'Route 211',
      channels: ['route-211'],
      types: ['Normal', 'Flying', 'Rock', 'Fighting'],
      wild: ['route-211'],
      trainers: ['hiker', 'psychic', 'camper'],
      noTrainers: [],
      common: ['Meditite', 'Bronzor', 'Machoke', 'Chingling', 'Hoothoot', 'Geodude'],
      rare: ['Clefairy', 'Absol'],
    },
    'route-212': {
      name: 'Route 212',
      channels: ['route-212'],
      types: ['Water', 'Bug', 'Normal', 'Poison'],
      wild: ['route-212'],
      trainers: ['fisherman', 'beauty', 'ranger', 'breeder', 'tuber'],
      noTrainers: [],
      common: ['Croagunk', 'Marill', 'Psyduck', 'Machoke', 'Wooper', 'Roselia', 'Shellos'],
      rare: ['Kricketune', 'Tympole'],
    },
    'route-213': {
      name: 'Route 213',
      channels: ['route-213'],
      types: ['Water', 'Normal', 'Flying'],
      wild: ['route-213'],
      trainers: ['swimmer', 'swimmerf', 'fisherman', 'tuber', 'sailor'],
      noTrainers: [],
      common: ['Wingull', 'Shellos', 'Buizel', 'Staravia', 'Machoke', 'Krabby'],
      rare: ['Finneon', 'Corphish'],
    },
    'route-214': {
      name: 'Route 214',
      channels: ['route-214'],
      types: ['Ground', 'Rock', 'Normal', 'Dark'],
      wild: ['route-214'],
      trainers: ['hiker', 'punk', 'delinquent', 'blackbelt'],
      noTrainers: [],
      common: ['Stunky', 'Girafarig', 'Houndour', 'Kricketune', 'Graveler', 'Skorupi'],
      rare: ['Gible', 'Absol'],
    },
    'route-215': {
      name: 'Route 215',
      channels: ['route-215'],
      types: ['Fighting', 'Normal', 'Water'],
      wild: ['route-215'],
      trainers: ['blackbelt', 'battlegirl', 'ninjaboy', 'acetrainer'],
      noTrainers: [],
      common: ['Machoke', 'Kricketune', 'Stunky', 'Houndour', 'Girafarig', 'Bibarel'],
      rare: ['Sneasel', 'Mienfoo'],
    },
    'route-216': {
      name: 'Route 216',
      channels: ['route-216'],
      types: ['Ice', 'Normal', 'Steel'],
      wild: ['route-216'],
      trainers: ['skier', 'hiker', 'blackbelt'],
      noTrainers: [],
      common: ['Snover', 'Sneasel', 'Meditite', 'Zubat', 'Snorunt', 'Swinub'],
      rare: ['Sneasel', 'Cubchoo'],
    },
    'route-217': {
      name: 'Route 217',
      channels: ['route-217'],
      types: ['Ice', 'Steel', 'Normal', 'Ghost'],
      wild: ['route-217'],
      trainers: ['skier', 'hiker', 'veteran'],
      noTrainers: [],
      common: ['Snover', 'Sneasel', 'Snorunt', 'Swinub', 'Zubat', 'Glalie'],
      rare: ['Delibird', 'Bergmite'],
    },
    'route-218': {
      name: 'Route 218',
      channels: ['route-218'],
      types: ['Water', 'Flying', 'Steel'],
      wild: ['route-218'],
      trainers: ['fisherman', 'swimmer', 'sailor'],
      noTrainers: [],
      common: ['Wingull', 'Buizel', 'Shellos', 'Machop', 'Magikarp'],
      rare: ['Finneon', 'Mantyke'],
    },
    'route-219': {
      name: 'Route 219',
      channels: ['route-219'],
      types: ['Water', 'Flying'],
      wild: ['route-219'],
      trainers: ['swimmer', 'swimmerf', 'fisherman'],
      noTrainers: [],
      common: ['Tentacool', 'Magikarp', 'Finneon', 'Wingull'],
      rare: ['Mantyke', 'Clamperl'],
    },
    'route-220': {
      name: 'Route 220',
      channels: ['route-220'],
      types: ['Water', 'Flying'],
      wild: ['route-220'],
      trainers: ['swimmer', 'swimmerf', 'sailor'],
      noTrainers: [],
      common: ['Tentacool', 'Magikarp', 'Finneon', 'Mantyke'],
      rare: ['Lumineon', 'Remoraid'],
    },
    'route-221': {
      name: 'Route 221',
      channels: ['route-221'],
      types: ['Normal', 'Grass', 'Flying'],
      wild: ['route-221'],
      trainers: ['breeder', 'pokefan', 'camper'],
      noTrainers: [],
      common: ['Staravia', 'Bibarel', 'Girafarig', 'Glameow', 'Stunky'],
      rare: ['Pachirisu', 'Dunsparce'],
    },
    'route-222': {
      name: 'Route 222',
      channels: ['route-222'],
      types: ['Electric', 'Water', 'Normal'],
      wild: ['route-222'],
      trainers: ['guitarist', 'swimmer', 'fisherman', 'acetrainer'],
      noTrainers: [],
      common: ['Wingull', 'Buizel', 'Floatzel', 'Electabuzz', 'Magikarp', 'Finneon'],
      rare: ['Chatot', 'Chinchou'],
    },
    'route-223': {
      name: 'Route 223',
      channels: ['route-223'],
      types: ['Water', 'Flying'],
      wild: ['route-223'],
      trainers: ['swimmer', 'swimmerf', 'sailor', 'veteran'],
      noTrainers: [],
      common: ['Tentacool', 'Mantyke', 'Wingull', 'Pelipper', 'Finneon'],
      rare: ['Remoraid', 'Wailmer'],
    },
    'route-224': {
      name: 'Route 224',
      channels: ['route-224'],
      types: ['Water', 'Grass', 'Flying'],
      wild: ['route-224'],
      trainers: ['veteran', 'acetrainerf', 'artist'],
      noTrainers: [],
      common: ['Staraptor', 'Bibarel', 'Roselia', 'Sudowoodo', 'Kricketune'],
      rare: ['Chatot', 'Tropius'],
    },
    'route-225': {
      name: 'Route 225',
      channels: ['route-225'],
      types: ['Fighting', 'Ground', 'Normal', 'Fire'],
      wild: ['route-225'],
      trainers: ['blackbelt', 'veteran', 'hiker', 'battlegirl'],
      noTrainers: [],
      common: ['Rhyhorn', 'Magmar', 'Machoke', 'Staraptor', 'Floatzel'],
      rare: ['Torkoal', 'Pawniard'],
    },
    'route-226': {
      name: 'Route 226',
      channels: ['route-226'],
      types: ['Flying', 'Rock', 'Water'],
      wild: ['route-226'],
      trainers: ['birdkeeper', 'swimmer', 'veteran'],
      noTrainers: [],
      common: ['Wingull', 'Pelipper', 'Skarmory', 'Golbat', 'Staraptor'],
      rare: ['Tropius', 'Rufflet'],
    },
    'route-227': {
      name: 'Route 227',
      channels: ['route-227'],
      types: ['Fire', 'Rock', 'Ground'],
      wild: ['route-227'],
      trainers: ['kindler', 'hiker', 'veteran', 'firebreather'],
      noTrainers: [],
      common: ['Numel', 'Camerupt', 'Magmar', 'Rhyhorn', 'Graveler', 'Slugma'],
      rare: ['Torkoal', 'Turtonator'],
    },
    'route-228': {
      name: 'Route 228',
      channels: ['route-228'],
      types: ['Ground', 'Rock', 'Steel'],
      wild: ['route-228'],
      trainers: ['ruinmaniac', 'hiker', 'veteran'],
      noTrainers: [],
      common: ['Cacnea', 'Sandslash', 'Hippopotas', 'Gligar', 'Trapinch'],
      rare: ['Larvitar', 'Silicobra'],
    },
    'route-229': {
      name: 'Route 229',
      channels: ['route-229'],
      types: ['Grass', 'Normal', 'Flying'],
      wild: ['route-229'],
      trainers: ['camper', 'picnicker', 'pokefan'],
      noTrainers: [],
      common: ['Staravia', 'Bibarel', 'Kricketune', 'Roselia', 'Pachirisu'],
      rare: ['Chatot', 'Buneary'],
    },
    'route-230': {
      name: 'Route 230',
      channels: ['route-230'],
      types: ['Water', 'Flying', 'Dragon'],
      wild: ['route-230'],
      trainers: ['swimmer', 'swimmerf', 'sailor', 'veteran'],
      noTrainers: [],
      common: ['Tentacruel', 'Mantyke', 'Pelipper', 'Wailmer', 'Finneon'],
      rare: ['Lumineon', 'Dratini'],
    },
  },
};
