/**
 * The buffs, for the client.
 *
 * Generated by scripts/build-buffs.js from data/velvet - do not edit by hand.
 * Regenerate it whenever a buff changes, or the builder will quietly go on
 * showing the old movepool.
 *
 * `bySpecies` is what each Pokemon gained and the full ability list it should
 * now have; the three tables after it are the moves, abilities and items this
 * server invented, which no CDN file has a row for.
 */
window.VelvetBuffs = {
	label: "Awakened",
	bySpecies: {
		"simisage": {
			"moves": [
				"grassyglide",
				"grassyterrain",
				"trailblaze",
				"growth",
				"endure",
				"terablast",
				"junglerush",
				"swordsdance",
				"bulkup",
				"focusenergy",
				"screech",
				"scaryface",
				"encore",
				"psychup",
				"spite",
				"curse",
				"quickguard",
				"metronome",
				"raindance",
				"closecombat",
				"drainpunch",
				"machpunch",
				"icepunch",
				"firepunch",
				"thunderpunch",
				"stoneedge",
				"uturn"
			],
			"abilities": [
				"Verdant Surge"
			],
			"slots": {
				"0": "Gluttony",
				"1": "Verdant Surge",
				"H": "Overgrow"
			}
		},
		"simisear": {
			"moves": [
				"temperflare",
				"burningjealousy",
				"ember",
				"endure",
				"terablast",
				"cinderrush",
				"swordsdance",
				"bulkup",
				"focusenergy",
				"screech",
				"scaryface",
				"encore",
				"psychup",
				"spite",
				"curse",
				"quickguard",
				"metronome",
				"raindance",
				"closecombat",
				"drainpunch",
				"machpunch",
				"icepunch",
				"thunderpunch",
				"stoneedge",
				"uturn"
			],
			"abilities": [
				"Solar Surge"
			],
			"slots": {
				"0": "Gluttony",
				"1": "Solar Surge",
				"H": "Blaze"
			}
		},
		"simipour": {
			"moves": [
				"liquidation",
				"chillingwater",
				"muddywater",
				"whirlpool",
				"wavecharge",
				"endure",
				"terablast",
				"torrentrush",
				"swordsdance",
				"bulkup",
				"focusenergy",
				"screech",
				"scaryface",
				"encore",
				"psychup",
				"spite",
				"curse",
				"quickguard",
				"metronome",
				"sunnyday",
				"closecombat",
				"drainpunch",
				"machpunch",
				"firepunch",
				"thunderpunch",
				"stoneedge",
				"uturn"
			],
			"abilities": [
				"Tidal Surge"
			],
			"slots": {
				"0": "Gluttony",
				"1": "Tidal Surge",
				"H": "Torrent"
			}
		}
	},
	moves: {"junglerush":{"num":-4,"name":"Jungle Rush","type":"Grass","category":"Physical","basePower":80,"accuracy":100,"pp":15,"priority":0,"target":"normal","flags":{"contact":1,"protect":1,"mirror":1,"metronome":1},"secondary":null,"shortDesc":"Uses the user's better attacking stat. +1 priority on Grassy Terrain.","desc":"This move uses whichever of the user's Attack or Special Attack is higher, before any boosts. It gains +1 priority while Grassy Terrain is active and the user is grounded."},"cinderrush":{"num":-6,"name":"Cinder Rush","type":"Fire","category":"Physical","basePower":80,"accuracy":100,"pp":15,"priority":0,"target":"normal","flags":{"contact":1,"protect":1,"mirror":1,"metronome":1},"secondary":null,"shortDesc":"Uses the user's better attacking stat. +1 priority in harsh sunlight.","desc":"This move uses whichever of the user's Attack or Special Attack is higher, before any boosts. It gains +1 priority in harsh sunlight."},"wavecharge":{"num":-5,"name":"Wave Charge","type":"Water","category":"Physical","basePower":50,"accuracy":100,"pp":20,"priority":0,"target":"normal","flags":{"contact":1,"protect":1,"mirror":1,"metronome":1},"secondary":{"chance":100,"self":{"boosts":{"spe":1}}},"shortDesc":"100% chance to raise the user's Speed by 1.","desc":"Has a 100% chance to raise the user's Speed by 1 stage."},"torrentrush":{"num":-7,"name":"Torrent Rush","type":"Water","category":"Physical","basePower":80,"accuracy":100,"pp":15,"priority":0,"target":"normal","flags":{"contact":1,"protect":1,"mirror":1,"metronome":1},"secondary":null,"shortDesc":"Uses the user's better attacking stat. +1 priority in rain.","desc":"This move uses whichever of the user's Attack or Special Attack is higher, before any boosts. It gains +1 priority in rain."}},
	abilities: {"verdantsurge":{"num":-3,"name":"Verdant Surge","rating":4,"shortDesc":"Sets Grassy Terrain on entry; this Pokemon's Grass moves get 1.5x from it instead of 1.3x.","desc":"On switch-in, this Pokemon summons Grassy Terrain. While Grassy Terrain is active and this Pokemon is grounded, its Grass-type moves are boosted to 1.5x rather than the usual 1.3x."},"solarsurge":{"num":-4,"name":"Solar Surge","rating":4,"shortDesc":"On switch-in, this Pokemon summons harsh sunlight.","desc":"On switch-in, the weather becomes harsh sunlight, which lasts until the weather is changed or five turns have passed. Held Heat Rock extends it to eight."},"tidalsurge":{"num":-5,"name":"Tidal Surge","rating":4,"shortDesc":"On switch-in, this Pokemon summons rain.","desc":"On switch-in, the weather becomes rain, which lasts until the weather is changed or five turns have passed. Held Damp Rock extends it to eight."}},
	items: {"elementalbanana":{"num":-1,"name":"Elemental Banana","spritenum":0,"itemUser":["Pansage","Simisage","Pansear","Simisear","Panpour","Simipour"],"fling":{"basePower":30},"gen":9,"shortDesc":"Simi family: 1.3x Atk, SpA and Speed, and cannot be removed. 1.5x after Tera/Dynamax, which also re-sets their weather.","desc":"If held by a Pansage, Pansear, Panpour, Simisage, Simisear or Simipour, that Pokemon's Attack, Special Attack and Speed are multiplied by 1.3, and the item cannot be removed by Knock Off, Trick, Thief or anything else. Once that Pokemon Terastallizes or Dynamaxes the multiplier becomes 1.5, and its weather- or terrain-setting Ability activates again."}},
	search: [["junglerush","move","0000001111"],["cinderrush","move","0000001111"],["wavecharge","move","0000111111"],["torrentrush","move","00000001111"],["verdantsurge","ability","000000011111"],["solarsurge","ability","0000011111"],["tidalsurge","ability","0000011111"],["elementalbanana","item","000000000111111"]],

	/** What this Pokemon gained, or an empty record. */
	get: function (speciesid) {
		return this.bySpecies[speciesid] || null;
	},
};
