'use strict';
/**
 * Teach Showdex's bundled damage calculator about our custom data.
 *
 *   node scripts/patch-showdex.js
 *
 * Showdex ships @smogon/calc inside its bundle, with its own tables of every
 * species, move, ability and item. There is no seam: the bundle is a sealed
 * IIFE with no module registry on the window, so nothing can reach those tables
 * from outside. The only way in is to edit the file, which is fine, because we
 * vendor it ourselves and rebuild it deliberately (see client/showdex/README).
 *
 * The edit is as small as it can be. Each of the four tables is published as an
 * array of per-generation tables - `e.SPECIES=[...]` and friends - and the
 * lookup the calculator actually reads is built from that array a few
 * statements later. So a single line inserted between the two, merging our data
 * into the last entry (which is generation 9), is enough: everything after it
 * builds from data that already includes ours.
 *
 * The data comes from window.__VELVET_CALC_DATA, generated by
 * scripts/build-calc-data.js and loaded before main.js.
 *
 * Idempotent, and every anchor is asserted: if a Showdex rebuild changes the
 * shape of any of these, this fails loudly here rather than silently shipping a
 * calculator that has quietly stopped knowing about half our server.
 */

const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '..', 'client', 'showdex', 'main.js');
const MARK = '/*velvet-calc*/';

/**
 * One hook per table.
 *
 * `merge` for the two that are objects keyed by name, `push` for the two that
 * are plain lists of names - the calculator only needs to recognise an ability
 * or an item, since what they do lives in its damage formula.
 */
const HOOKS = [
	{ table: 'SPECIES', anchor: 'e.SPECIES=[h,o,l,a,s,c,u,d,p,f];', key: 'species', kind: 'merge' },
	{ table: 'MOVES', anchor: 'e.MOVES=[f,i,o,l,a,s,c,u,d,m];', key: 'moves', kind: 'merge' },
	{ table: 'ITEMS', anchor: 'e.ITEMS=[g,[],i,l,a,s,u,d,p,f];', key: 'items', kind: 'push' },
	{ table: 'ABILITIES', anchor: null, key: 'abilities', kind: 'push' },
];

function hookFor({ table, key, kind }) {
	const target = `e.${table}[e.${table}.length-1]`;
	const apply = kind === 'merge' ?
		`Object.assign(${target},D.${key})` :
		`D.${key}.forEach(function(n){if(${target}.indexOf(n)<0)${target}.push(n)})`;

	/*
	 * Each hook says so afterwards, on the window.
	 *
	 * Not decoration: these tables are module-local and the calculator is not
	 * callable from outside the bundle, so without this the only thing that
	 * could be checked is that the text was inserted - which is not the same as
	 * it having run, and is exactly the kind of "verification" that passes while
	 * the feature is broken. The note records what the table actually contains
	 * afterwards, so a probe can confirm the merge landed rather than the line
	 * existing.
	 */
	const note = `window.__VELVET_CALC_APPLIED=(window.__VELVET_CALC_APPLIED||{});` +
		`window.__VELVET_CALC_APPLIED.${key}=${kind === 'merge' ?
			`Object.keys(${target}).length` : `${target}.length`};`;

	return `${MARK}try{var D=window.__VELVET_CALC_DATA;if(D&&D.${key}){${apply};${note}}}catch(_e){}`;
}

let source = fs.readFileSync(FILE, 'utf8');
if (source.includes(MARK)) {
	console.log('already patched; nothing to do');
	process.exit(0);
}

let patched = 0;
for (const hook of HOOKS) {
	let anchor = hook.anchor;
	if (!anchor) {
		// ABILITIES is published as a literal array of arrays rather than a list
		// of variables, so its anchor has to be found rather than written down.
		const at = source.indexOf(`e.${hook.table}=[[`);
		if (at < 0) throw new Error(`could not find where ${hook.table} is published`);
		const end = source.indexOf('];', at);
		if (end < 0) throw new Error(`could not find the end of the ${hook.table} table`);
		anchor = source.slice(at, end + 2);
	}

	const count = source.split(anchor).length - 1;
	if (count !== 1) {
		throw new Error(`${hook.table}: expected exactly one publish point, found ${count} - ` +
			`Showdex's bundle has changed shape and this patch needs rechecking`);
	}
	source = source.replace(anchor, anchor + hookFor(hook));
	patched++;
	console.log(`  ${hook.table}: hooked (${hook.kind})`);
}

fs.writeFileSync(FILE, source);
console.log(`patched ${patched} table(s) in ${FILE}`);
